### ISSUE TITLE
Entering arena mode with RegionCast never finishes loading.

### ISSUE THREAD

**Issue by FrostBird347** [casheww/RW-RegionCast#11]
Pausing while the level is loading will show the level, however all controls will still be locked after unpausing and time won't pass in game.

I am currently unable to obtain the exception log. I will upload it here when I can.

**Comment by casheww** [comment]
I haven't experienced this myself - will test later.
exceptionLog would be much appreciated when you can get hold of it

**Comment by casheww** [comment]
managed to reproduce, and it should now be fixed - try out the [latest release](https://github.com/casheww/RW-RegionCast/releases/tag/v0.5.1) 
do let me know if there are any other issues - thanks!
