### ISSUE TITLE
Custom Region : Arid Barrens

### ISSUE THREAD

**Issue by Precipitator80** [casheww/RW-RegionCast#12]
1. Arid Barrens
2. AB
3. https://drive.google.com/file/d/1PysxNcrZHjgVLBR-Z-JSs7LrerpfmD8A/view?usp=sharing [Copy is also attached below]
![Main Region Art _ Thumbnail](https://user-images.githubusercontent.com/52417640/105638782-9ab58b80-5e6c-11eb-93ae-d6ca4dbfdfc2.PNG)

**Comment by casheww** [comment]
Forgot to post here; AB details have been added and the asset uploaded to Discord - tested earlier and it's up and working 👍
