### ISSUE TITLE
README does not instruct installing .NET Core 3.1 Runtime

### ISSUE THREAD

**Issue by PJB3005** [casheww/RW-RegionCast#7]
The helper program you're shipping with the mod to handle actual rich presence support targets .NET Core 3.1, but you're shipping it as a framework-dependent publish, so the runtime has to be installed on the user's machine. You should probably mention this in the README?

(Side note: you could probably use https://www.nuget.org/packages/DiscordRichPresence/ which should run on .NET Framework 3.5 and require no funny separate-program dependencies?)

**Comment by casheww** [comment]
I assume the runtime is something that's installed on Windows 10 by default? Seeing as it's not an issue I've seen anyone else run into. I'm pretty new to the .NET game if you couldn't already tell lol. I will look into it, thanks!

On the DRP package from Lachee: I have seen it before, and am playing around with it when I have some spare time, but it does require a significant rejig of the project - my focus has been on adding more QoL features. I also understand that it uses the old Rich Presence setup which has been "deprecated" by Discord - even if that's just referring to the client-side package to interact with their API - which makes it seem like a technological step back. I agree that the side-app is a little funky, but it works fine at the moment.

**Comment by casheww** [comment]
After a quick search, I think I understand. I will add this note to the README shortly. Thanks for bringing this up!

**Comment by PJB3005** [comment]
> I assume the runtime is something that's installed on Windows 10 by default?

.NET Core/.NET 5 isn't anymore, and because .NET Core has self contained publishes now I think that's what most software using it (which still isn't much for desktop apps I don't think) publishes with, it's also less likely to get installed as part of some random program (like .NET Framework used to back in the day before Windows shipped it automatically)

**Comment by casheww** [comment]
> (Side note: you could probably use https://www.nuget.org/packages/DiscordRichPresence/ which should run on .NET Framework 3.5 and require no funny separate-program dependencies?)

Apparently, the version of mscorlib that Rain World uses does not have some of the stuff required for Lachee's package / Newtonsoft.Json, so this seems unfortunately impractical.

**Comment by PJB3005** [comment]
Ah well, shame.
